format_version: 10
pipelines:
  air-backend:
    group: air
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      frontend-repo:
        git: https://github.com/thebestlearner-ric/airport-frontend.git
        username: thebestlearner-ric
        shallow_clone: false
        auto_update: true
        branch: main
        encrypted_password: AES:PHp/CacxfxowpJmo7K92xw==:GWG53xoLL5a4svzdBrjqpw==
        destination: air-frontend-repo
      air-backend-conf:
        git: https://github.com/thebestlearner-ric/gocd-config.git
        username: thebestlearner-ric
        shallow_clone: false
        auto_update: true
        branch: frontend
        encrypted_password: AES:PHp/CacxfxowpJmo7K92xw==:GWG53xoLL5a4svzdBrjqpw==
        destination: air-frontend-repo-config
    stages:
    - Build-and-Publish:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          docker:
            timeout: 0
            elastic_profile_id: demo-app
            tasks:
            - exec:
                command: bash 
                arguments:
                  - -c
                  - |
                    cd air-frontend-repo-config
                    bash scripts/build.sh frontend
    - Kube-deploy:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          dockerpush:
            timeout: 0
            elastic_profile_id: demo-app
            tasks:
            - exec:
                command: bash 
                arguments:
                  - -c 
                  - |
                    curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
                    chmod +x kubectl
                    mkdir -p ~/.local/bin
                    mv kubectl $HOME/.local/bin/kubectl
                    export PATH="$PATH:$HOME/.local/bin"
                privileged: true
            - exec:
                command: bash 
                arguments:
                  - -c
                  - |
                    cd air-frontend-repo-config
                    bash scripts/deploy.sh frontend