apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2 # Adjust as needed
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: IMAGE # Replace with actual image and tag
          ports:
            - containerPort: 5000
